project: 
  type: website

website:
  title: "Miya Huang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - text : Homework
        menu:
          - href: homework/hw1_questions.qmd
            text: HW1
          - href: homework/hw2_questions.qmd
            text: HW2

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



